name: 'Setup'
description: 'Initialize a github actions runner for CI jobs.'
inputs:
  java-version:
    description: "The java version to install."
    required: true
    default: "8"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: setup java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "corretto"
    - run: java -version
      shell: bash
    - run: python --version
      shell: bash
    - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash
    - run: uv --version
      shell: bash
    - run: uv sync --only-group scripting --no-install-project
      shell: bash
