name: 'Setup'
description: 'Initialize a github actions runner for CI jobs.'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: java -version
      shell: bash
    - run: python --version
      shell: bash
    - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash
    - run: uv --version
      shell: bash
    - run: uv sync --only-group scripting --no-install-project
      shell: bash
